from typing import Literal
from langgraph.graph import StateGraph, START, END
from backend.state import CompanionState

from backend.nodes import (
    retrieve_episodic_memory,
    retrieve_long_term_memory,
    generate_response,
    save_conversation,
    generate_conversation_embedding,
    store_conversation_embedding,
    extract_memory,
    compare_candidate_memory,
    save_long_term_memory,
)

# ============================================================
# Memory Decision Router
# ============================================================

def route_memory_decision(
    state: CompanionState,
) -> Literal["save_long_term_memory", "end"]:
    """
    Determines whether the graph should proceed to save long-term memory.
    It checks the 'memory_decision_list' generated by the comparison node.
    """
    decisions = state.get("memory_decision_list", [])

    # If no memories were extracted (e.g., general knowledge question), finish the turn.
    if not decisions:
        print("\n[Router] No personal facts to process. Ending.")
        return "end"

    # Check if there is at least one fact that is NEW or an UPDATE.
    # This prevents redundant database writes for SAME facts.
    has_changes = any(d['decision'] in ("NEW", "UPDATE") for d in decisions)

    if has_changes:
        print(f"\n[Router] Found {len(decisions)} items. Proceeding to Save.")
        return "save_long_term_memory"
    
    print("\n[Router] All extracted facts already exist (SAME). Ending.")
    return "end"


# ============================================================
# Graph Orchestration
# ============================================================

builder = StateGraph(CompanionState)

# 1. Register all Processing Nodes
builder.add_node("retrieve_episodic_memory", retrieve_episodic_memory)
builder.add_node("retrieve_long_term_memory", retrieve_long_term_memory)
builder.add_node("generate_response", generate_response)
builder.add_node("save_conversation", save_conversation)
builder.add_node("generate_conversation_embedding", generate_conversation_embedding)
builder.add_node("store_conversation_embedding", store_conversation_embedding)
builder.add_node("extract_memory", extract_memory)
builder.add_node("compare_candidate_memory", compare_candidate_memory)
builder.add_node("save_long_term_memory", save_long_term_memory)

# 2. Define the Main Conversation Flow
builder.add_edge(START, "retrieve_episodic_memory")
builder.add_edge("retrieve_episodic_memory", "retrieve_long_term_memory")
builder.add_edge("retrieve_long_term_memory", "generate_response")
builder.add_edge("generate_response", "save_conversation")
builder.add_edge("save_conversation", "generate_conversation_embedding")
builder.add_edge("generate_conversation_embedding", "store_conversation_embedding")
builder.add_edge("store_conversation_embedding", "extract_memory")
builder.add_edge("extract_memory", "compare_candidate_memory")

# 3. Define the Conditional Memory Branch
# If facts were found, save them; otherwise, end the turn.
builder.add_conditional_edges(
    "compare_candidate_memory",
    route_memory_decision,
    {
        "save_long_term_memory": "save_long_term_memory",
        "end": END,
    }
)

# 4. Finalize the Memory Operation
builder.add_edge("save_long_term_memory", END)

# 5. Compile the Workflow
graph = builder.compile()